name: Demo-2

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create a text file
      run: echo "Hello, world!" > hello.txt
    - uses: actions/upload-artifact@v7
      with:
        name: hello-file
        path: hello.txt
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v8
      with:
        name: hello-file
    - name: List all files
      run: ls
    - name: Test file
      run: cat hello.txt | grep -i "Hello, world!"
  
